# Generated by Django 4.2.2 on 2023-06-06 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comments',
            new_name='commenter',
        ),
    ]
